In [22]:
import pandas as pd
import sqlite3

file_path = r"C:\Users\æ®µ\Desktop\724\Renewable_Energy_Adoption.csv"
df = pd.read_csv(file_path)
df.index = range(1, len(df) + 1)

pd.get_option('display.max_rows')
pd.set_option('display.max_rows', 300)

# Calculate the government investment component
country_averages = {}

for country in df['Country'].unique():
    country_data = df[df['Country'] == country]
    avg_investment = country_data['Government Investment (Million USD)'].mean()
    country_averages[country] = avg_investment

for index, row in df.iterrows():
    if pd.isnull(row['Government Investment (Million USD)']):
        current_country = row['Country']
        avg_value = country_averages[current_country]
        df.at[index, 'Government Investment (Million USD)'] = avg_value


def none_values(row):
    energy_cols = ['Solar', 'Wind', 'Hydro', 'Geothermal', 'Biomass', 'Other Renewables']

    if pd.isnull(row['Renewable Energy (%)']):
        total = 0
        for col in energy_cols:
            if pd.isnull(row[col]):
                total += 0
            else:
                total += row[col]
        row['Renewable Energy (%)'] = total

    else:
        missing_count = 0
        missing_col = None
        known_sum = 0
        for col in energy_cols:
            if pd.isnull(row[col]):
                missing_count += 1
                missing_col = col
            else:
                known_sum += row[col]

        if missing_count == 1:
            row[missing_col] = row['Renewable Energy (%)'] - known_sum
        else:

    return row

df = df.apply(none_values, axis=1)

df.head(30)

,Country,Year,Total Energy Consumption (TWh),Renewable Energy (%),Government Investment (Million USD),Emissions Reduction (%),Solar,Wind,Hydro,Geothermal,Biomass,Other Renewables
1,USA,2000,2383,7.027076,279.000000,2.063344,1.355129,0.316245,0.614757,1.195410,1.291793,2.253741
2,USA,2001,2734,6.816378,384.000000,1.037638,0.708988,1.285245,0.003853,0.906582,1.337339,2.574371
3,USA,2002,1607,9.538258,109.000000,2.220549,0.137875,0.781596,1.491820,0.745947,1.415221,4.965798
4,USA,2003,3587,4.334616,282.000000,0.724672,0.601906,0.758459,0.613620,0.365135,0.764292,1.231205
5,USA,2004,2363,5.678810,161.000000,0.856833,NaN,0.443610,0.507574,0.702281,0.905387,3.119958
6,USA,2005,2667,5.478015,262.000000,0.762587,0.291994,1.049155,0.464965,1.046326,0.745024,1.880552
7,USA,2006,3874,1.147660,282.090909,0.670731,NaN,0.383173,0.191738,0.006189,0.566561,NaN
8,USA,2007,2709,4.502549,336.000000,0.822222,0.409173,0.427606,0.810605,0.447382,0.357671,2.050112
9,USA,2008,3619,3.062048,156.000000,0.763238,0.345700,0.079211,0.343720,0.481329,0.008739,1.803350
10,USA,2009,4011,7.926514,298.000000,2.106443,1.021701,1.056588,0.153461,0.611487,0.737245,4.346032
11,USA,2010,2966,32.172057,78.000000,7.428388,0.418292,4.274297,5.357837,3.601392,3.658519,14.861720
12,USA,2011,4842,27.656816,166.000000,6.656912,1.321923,1.629374,4.701044,4.876275,4.454350,10.673851
13,USA,2012,2781,17.609545,282.090909,4.739114,1.534058,1.746072,3.458869,1.850836,1.567086,7.452623
14,USA,2013,2491,30.731140,411.000000,8.481723,7.083589,2.776481,3.483269,NaN,5.165254,12.222547
15,USA,2014,3728,27.784396,385.000000,5.891041,0.086299,3.881353,3.052233,1.135108,0.163827,19.465576
16,USA,2015,4205,19.083021,487.000000,3.344366,0.554016,3.742625,2.284886,2.214240,1.399923,8.887330
17,USA,2016,2532,13.094411,423.000000,3.541573,1.808887,2.531828,0.864091,1.959765,2.390027,3.539813
18,USA,2017,2291,13.736608,326.000000,3.672300,1.664942,1.421050,0.990245,0.392104,0.801843,8.466423
19,USA,2018,1734,13.796906,186.000000,4.093743,2.237930,2.746056,1.068132,0.304352,NaN,7.440436
20,USA,2019,4340,14.188257,65.000000,3.791718,0.427327,0.201128,1.675875,1.054204,2.192924,8.636799
21,USA,2020,4642,73.799742,400.000000,10.029115,7.836101,12.818500,2.255955,1.274215,10.998972,38.615999
22,USA,2021,2294,72.844823,280.000000,19.664389,1.812821,1.248775,5.636252,0.109747,2.405992,51.545522
23,USA,2022,4856,52.220468,347.000000,13.888763,3.745713,4.740272,5.110562,4.916673,7.735940,25.971309
24,USA,2023,2268,41.205131,385.000000,6.277225,3.074045,2.188639,3.789179,2.879556,3.159691,10.909673
25,China,2000,1246,9.994497,319.000000,2.052109,0.113965,1.544674,1.967169,0.393627,1.234266,4.740797
26,China,2001,4728,5.586013,260.476190,0.667173,0.787336,0.261348,0.320990,0.609320,0.042998,3.564021
27,China,2002,1569,0.822262,113.000000,0.219153,0.115620,0.138253,0.021237,0.068100,0.039231,0.439822
28,China,2003,1444,3.977524,458.000000,0.848215,0.765899,0.722043,0.140394,0.165171,0.106824,2.077192
29,China,2004,4138,2.757652,254.000000,0.439336,0.088701,0.200930,0.546731,0.186566,0.217754,1.516970
30,China,2005,3257,3.646131,304.000000,0.963992,0.669098,0.532976,0.456747,0.077858,0.539645,1.369807